## Array indexing

Numpy offers several ways to index into arrays and accessing/changing specific elements, rows, columns, etc.

**Slicing:** Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [9]:
import numpy as np
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Indexing a 1D array

In [10]:
a[2]           # Get a value at an index

2

In [11]:
a[1:4]         # Get values in a range / slice notation

array([1, 2, 3])

In [12]:
a[:6]

array([0, 1, 2, 3, 4, 5])

In [13]:
a[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#Slices
slice_a = a[0:5]
slice_a

array([0, 1, 2, 3, 4])

In [15]:
a_copy = a.copy()   # creat a copy

a_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
a_copy[:]=200
a_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [17]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Be careful when copying arrays!!!

In [19]:
a = np.array([1,2,3])
a

b = a
#b = a.copy()
b[0] = 100

print(a) 

[100   2   3]


In [20]:
a = np.array([1,2,3])
a

# b = a
b = a.copy()
b[0] = 100

print(a) 
print(b)

[1 2 3]
[100   2   3]


#### Indexing a 2D array (matrices)

In [ ]:
# mat = [row,col]
# mat = [row][col]

In [21]:
mat=np.array(([5,10,20],[20,25,30],[35,40,10]))
mat

array([[ 5, 10, 20],
       [20, 25, 30],
       [35, 40, 10]])

In [24]:
mat[0] #Indexing row

array([ 5, 10, 20])

In [22]:
mat[1] #Indexing row

array([20, 25, 30])

In [23]:
mat[2]

array([35, 40, 10])

In [25]:
# Getting individual element value
mat[1][1]

25

In [26]:
mat[1,2] # use common notaion instaed of 2 brackets

30

In [ ]:
# 3D example

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Summary:

In [27]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [30]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"

77


In [31]:
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

77


### Quiz time

In [ ]:
# Generate matrix:

###    1  2  3  4  5
###    6  7  8  9 10
###   11 12 13 14 15
###   16 17 18 19 20
###   21 22 23 24 25
###   26 27 28 29 30

# Acces 
        11 12
        16 17
    
# Acces  
         2
           8
            14
              20

# Acces        
                4  5



               24 25
               29 30

### Boolean array indexing

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [32]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
a > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [36]:
a[a>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
x = 2
a[a>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

For brevity we have left out a lot of details about numpy array indexing; if you want to know more about Array Indexing you should read this **[documentation](https://numpy.org/doc/stable/reference/arrays.indexing.html)**.