## Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [1]:
import numpy as np

a = np.array([0,1,2,3,4,5])
print(a)

[0 1 2 3 4 5]


In [2]:
a + 2

array([2, 3, 4, 5, 6, 7])

In [3]:
a - 2

array([-2, -1,  0,  1,  2,  3])

In [4]:
a * 2

array([ 0,  2,  4,  6,  8, 10])

In [5]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [6]:
a + a

array([ 0,  2,  4,  6,  8, 10])

In [7]:
a * a

array([ 0,  1,  4,  9, 16, 25])

In [8]:
a - a

array([0, 0, 0, 0, 0, 0])

In [9]:
a/a # Warning on division by zero, but not an error!

<ipython-input-9-1b9ae9b69587>:1: RuntimeWarning: invalid value encountered in true_divide
  a/a # Warning on division by zero, but not an error!


array([nan,  1.,  1.,  1.,  1.,  1.])

In [10]:
1/a # Also warning, but not an error instead infinity

<ipython-input-10-6f47904706aa>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/a # Also warning, but not an error instead infinity


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       ])

### Universal  Array Functions (Mathematical operations)

In [14]:
a

array([0, 1, 2, 3, 4, 5])

In [15]:
#Square Roots
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [16]:
#exponential (e^)
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [22]:
np.max(a) #same as arr.max()

5

In [23]:
np.min(a)

0

In [24]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [25]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219])

In [31]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [32]:
# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [33]:
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [34]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [35]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [36]:
### Dot product: product of two arrays

f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)

14

In [37]:
import numpy as np

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


Numpy provides many useful functions for performing computations on arrays; one of the most useful is **`sum`**:

In [39]:
import numpy as np

x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x))  # Compute sum of all elements; prints "10"

[[1 2]
 [3 4]]
10


You can find the full list of mathematical functions provided by numpy in this **[documentation](https://numpy.org/doc/stable/reference/routines.math.html)**.

Numpy provides many more functions for manipulating arrays; you can see the full list in the **[documentation](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)**.

### Matrix Multiplication

The Numpy **`matmul()`** function is used to return the matrix product of 2 arrays.

In [43]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b) # matmul() function is used to return the matrix product of 2 arrays. 

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [46]:
### Matmul: matruc product of two arrays

h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
print("Multiplication: ")
### 1*5+2*7 = 19
np.matmul(h, i)

Multiplication: 


array([[19, 22],
       [43, 50]])