## Arrays reorganizing

### `arange()`

The **`arange()`** is an inbuilt numpy function that returns an ndarray object containing evenly spaced values within a defined interval. For instance, you want to create values from 1 to 10; you can use **`arange()`** function.

**Syntax:**
```python
numpy.arange(start, stop,step) 
```
* **`start`**: Start of interval
* **`stop`**: End of interval
* **`step`**: Spacing between values. Default step is 1

In [1]:
# Example 1:

import numpy as np
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

If you want to change the step, you can add a third number in the parenthesis. It will change the step.

In [2]:
# Example 2:

import numpy as np
np.arange(1, 14, 4)

array([ 1,  5,  9, 13])

In [3]:
np.arange(0,11,2)   # even no by adding a step size

array([ 0,  2,  4,  6,  8, 10])

In [4]:
np.arange(1,11,2)   # odd no

array([1, 3, 5, 7, 9])

### Reshape Data

In some occasions, you need to reshape the data from wide to long. You can use the reshape function for this. 

**Syntax:** 
```python
numpy.reshape(a, newShape, order='C')
```
* **`a: Array`** that you want to reshape
* **`newShape`**: The new desires shape
* **`order`**: Default is **`C`** which is an essential row style.

In [6]:
import numpy as np

e  = np.array([(1,2,3), (4,5,6)])
print(e)
print(e.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
new_e = e.reshape(3,2)
new_e

array([[1, 2],
       [3, 4],
       [5, 6]])

### Flatten Data

When you deal with some neural network like convnet, you need to flatten the array. You can use **`flatten()`**.

**Syntax:** 
```python
numpy.flatten(order='C')
```
* **`a: Array`** that you want to reshape
* **`newShape`**: The new desires shape
* **`order`**: Default is **`C`** which is an essential row style.

In [10]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

### What is `hstack`?

With **`hstack`** you can appened data horizontally. This is a very convinient function in Numpy. Lets study it with an example:

In [14]:
## Horitzontal Stack

import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [15]:
# Horizontal  stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### What is `vstack`?

With **`vstack`** you can appened data vertically. Lets study it with an example:

In [16]:
## Vertical Stack

import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [20]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

## Statistics

NumPy has quite a few useful statistical functions for finding minimum, maximum, percentile standard deviation and variance, etc from the given elements in the array. The functions are explained as follows −

Numpy is equipped with the robust statistical function as listed below:

| Function | Numpy |
|:----: |:---- |
| **`Min`**                | **np.min()** | 
| **`Max`**                | **np.max()** | 
| **`Mean`**               | **np.mean()** | 
| **`Median`**             | **np.median()** | 
| **`Standard deviation`** | **np.std()** | 

In [26]:
# Consider the following Array

import numpy as np

normal_array = np.array([1, 2, 3, 4, 5, 6, 7])

In [27]:
# Example:Statistical function

### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

1
7
4.0
4.0
2.0


## Numpy Documentation

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the **[numpy reference](https://numpy.org/doc/stable/reference/)** to find out much more about numpy.